version: '3'
services:
  client:
    build: ./Client
    ports:
      - '80:3000'
    depends_on:
      - server
  server:
    build: ./Server
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'

